wandb_version: 1

model:
  desc: null
  value: RandomForestClassifier
n_estimators:
  desc: null
  value: 10
maxdepth:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684705085.227635
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.8
      5: 0.15.3
      8:
      - 5
